contractions_as_key = {
  "ain't": "am not",
  "aren't": "are not",
  "can't": "cannot",
  "can't've": "cannot have",
  "'cause": "because",
  "could've": "could have",
  "couldn't": "could not",
  "couldn't've": "could not have",
  "didn't": "did not",
  "doesn't": "does not",
  "don't": "do not",
  "hadn't": "had not",
  "hadn't've": "had not have",
  "hasn't": "has not",
  "haven't": "have not",
  "he'd": "he would",
  "he'd've": "he would have",
  "he'll": "he will",
  "he'll've": "he will have",
  "here's": "here is",
  "he's": "he is",
  "how'd": "how did",
  "how'd'y": "how do you",
  "how'll": "how will",
  "how's": "how is",
  "I'd": "I would",
  "I'd've": "I would have",
  "I'll": "I will",
  "I'll've": "I will have",
  "I'm": "I am",
  "I've": "I have",
  "isn't": "is not",
  "it'd": "it had",
  "it'd've": "it would have",
  "it'll": "it will",
  "it'll've": "it will have",
  "it's": "it is",
  "let's": "let us",
  "ma'am": "madam",
  "mayn't": "may not",
  "might've": "might have",
  "mightn't": "might not",
  "mightn't've": "might not have",
  "must've": "must have",
  "mustn't": "must not",
  "mustn't've": "must not have",
  "needn't": "need not",
  "needn't've": "need not have",
  "o'clock": "of the clock",
  "oughtn't": "ought not",
  "oughtn't've": "ought not have",
  "shan't": "shall not",
  "sha'n't": "shall not",
  "shan't've": "shall not have",
  "she'd": "she would",
  "she'd've": "she would have",
  "she'll": "she will",
  "she'll've": "she will have",
  "she's": "she is",
  "should've": "should have",
  "shouldn't": "should not",
  "shouldn't've": "should not have",
  "so've": "so have",
  "so's": "so is",
  "that'd": "that would",
  "that'd've": "that would have",
  "that's": "that is",
  "there'd": "there had",
  "there'd've": "there would have",
  "there's": "there is",
  "they'd": "they would",
  "they'd've": "they would have",
  "they'll": "they will",
  "they'll've": "they will have",
  "they're": "they are",
  "they've": "they have",
  "to've": "to have",
  "wasn't": "was not",
  "we'd": "we had",
  "we'd've": "we would have",
  "we'll": "we will",
  "we'll've": "we will have",
  "we're": "we are",
  "we've": "we have",
  "weren't": "were not",
  "what'll": "what will",
  "what'll've": "what will have",
  "what're": "what are",
  "what's": "what is",
  "what've": "what have",
  "when's": "when is",
  "when've": "when have",
  "where'd": "where did",
  "where's": "where is",
  "where've": "where have",
  "who'll": "who will",
  "who'll've": "who will have",
  "who's": "who is",
  "who've": "who have",
  "why's": "why is",
  "why've": "why have",
  "will've": "will have",
  "won't": "will not",
  "won't've": "will not have",
  "would've": "would have",
  "wouldn't": "would not",
  "wouldn't've": "would not have",
  "y'all": "you all",
  "y'alls": "you alls",
  "y'all'd": "you all would",
  "y'all'd've": "you all would have",
  "y'all're": "you all are",
  "y'all've": "you all have",
  "you'd": "you had",
  "you'd've": "you would have",
  "you'll": "you will",
  "you'll've": "you will have",
  "you're": "you are",
  "you've": "you have"
}
expanded_as_key = {
    'am not': "ain't",
    'are not': "aren't",
    'cannot': "can't",
    'cannot have': "can't've",
    'because': "'cause",
    'could have': "could've",
    'could not': "couldn't",
    'could not have': "couldn't've",
    'did not': "didn't",
    'does not': "doesn't",
    'do not': "don't",
    'had not': "hadn't",
    'had not have': "hadn't've",
    'has not': "hasn't",
    'have not': "haven't",
    'he would': "he'd",
    'he would have': "he'd've",
    'he will': "he'll",
    'he will have': "he'll've",
    'here is': "here's",
    'he is': "he's",
    'how did': "how'd",
    'how do you': "how'd'y",
    'how will': "how'll",
    'how is': "how's",
    'I would': "I'd",
    'I would have': "I'd've",
    'I will': "I'll",
    'I will have': "I'll've",
    'I am': "I'm",
    'I have': "I've",
    'is not': "isn't",
    'it had': "it'd",
    'it would have': "it'd've",
    'it will': "it'll",
    'it will have': "it'll've",
    'it is': "it's",
    'let us': "let's",
    'madam': "ma'am",
    'may not': "mayn't",
    'might have': "might've",
    'might not': "mightn't",
    'might not have': "mightn't've",
    'must have': "must've",
    'must not': "mustn't",
    'must not have': "mustn't've",
    'need not': "needn't",
    'need not have': "needn't've",
    'of the clock': "o'clock",
    'ought not': "oughtn't",
    'ought not have': "oughtn't've",
    'shall not': "sha'n't",
    'shall not have': "shan't've",
    'she would': "she'd",
    'she would have': "she'd've",
    'she will': "she'll",
    'she will have': "she'll've",
    'she is': "she's",
    'should have': "should've",
    'should not': "shouldn't",
    'should not have': "shouldn't've",
    'so have': "so've",
    'so is': "so's",
    'that would': "that'd",
    'that would have': "that'd've",
    'that is': "that's",
    'there had': "there'd",
    'there would have': "there'd've",
    'there is': "there's",
    'they would': "they'd",
    'they would have': "they'd've",
    'they will': "they'll",
    'they will have': "they'll've",
    'they are': "they're",
    'they have': "they've",
    'to have': "to've",
    'was not': "wasn't",
    'we had': "we'd",
    'we would have': "we'd've",
    'we will': "we'll",
    'we will have': "we'll've",
    'we are': "we're",
    'we have': "we've",
    'were not': "weren't",
    'what will': "what'll",
    'what will have': "what'll've",
    'what are': "what're",
    'what is': "what's",
    'what have': "what've",
    'when is': "when's",
    'when have': "when've",
    'where did': "where'd",
    'where is': "where's",
    'where have': "where've",
    'who will': "who'll",
    'who will have': "who'll've",
    'who is': "who's",
    'who have': "who've",
    'why is': "why's",
    'why have': "why've",
    'will have': "will've",
    'will not': "won't",
    'will not have': "won't've",
    'would have': "would've",
    'would not': "wouldn't",
    'would not have': "wouldn't've",
    'you all': "y'all",
    'you alls': "y'alls",
    'you all would': "y'all'd",
    'you all would have': "y'all'd've",
    'you all are': "y'all're",
    'you all have': "y'all've",
    'you had': "you'd",
    'you would have': "you'd've",
    'you will': "you'll",
    'you will have': "you'll've",
    'you are': "you're",
    'you have': "you've"
}
